dir:
  working_dir: $HOME/Universal-NGS-workflow
  metadata: $HOME/Universal-NGS-workflow/metadata.csv

param:
  type: RNA-seq
  # RNA-seq, ChIP-seq, ATAC-seq, WGS
  layout: pe
  # Single-end: se; Pair-end: pe
  use_slurm: True
  # True/False

workflow:
  - spades
#  - fastqc
#  - cutadapt
#  - trimmomatic
#  - fastqc
#  - salmon
